from numba import float32
from pyHype.states import ConservativeState, PrimitiveState

ROE_FLUX_X_SPEC = [('gh', float32),
                   ('gt', float32),
                   ('gb', float32),
                   ('g', float32),
                   ('_input', dict),
                   ('_L', ConservativeState.class_type.instance_type),
                   ('_R', ConservativeState),
                   ('A_d', float32[:]),
                   ('A_m1', float32[:]),
                   ('A_m2', float32[:]),
                   ('A_m3', float32[:]),
                   ('A_p1', float32[:]),
                   ('A_p2', float32[:]),
                   ('X_d', float32[:]),
                   ('X_m1', float32[:]),
                   ('X_m2', float32[:]),
                   ('X_m3', float32[:]),
                   ('X_p1', float32[:]),
                   ('X_p2', float32[:]),
                   ('Xi_d', float32[:]),
                   ('Xi_m1', float32[:]),
                   ('Xi_m2', float32[:]),
                   ('Xi_m3', float32[:]),
                   ('Xi_p1', float32[:]),
                   ('Xi_p2', float32[:]),
                   ('Xi_p3', float32[:]),
                   ]