implosion = {'problem_type': 'implosion',
             'IC_type': 'from_IC',
             'flux_function': 'Roe',
             'realplot': 1,
             'make_plot': 1,
             'time_it': 1,
             't_final': 0.005,
             'time_integrator': 'RK2',
             'CFL': 0.55,
             'finite_volume_method': 'SecondOrderLimited',
             'flux_limiter': 'van_albada',
             'gamma': 1.1,
             'rho_inf': 1.0,
             'a_inf': 343.0,
             'R': 287.0,
             'nx': 200,
             'ny': 200,
             'mesh_name': 'one_mesh'}

