implosion = {'problem_type':            'implosion',
             'IC_type':                 'from_IC',
             'flux_function':           'Roe',
             'reconstruction_type':     'Primitive',
             'realplot':                1,
             'makeplot':                1,
             'time_it':                 1,
             't_final':                 0.007,
             'time_integrator':         'RK2',
             'CFL':                     0.5,
             'finite_volume_method':    'SecondOrderGreenGauss',
             'flux_limiter':            'van_albada',
             'gamma':                   1.4,
             'rho_inf':                 1.0,
             'a_inf':                   343.0,
             'R':                       287.0,
             'nx':                      100,
             'ny':                      100,
             'mesh_name':               'one_mesh'}

