from numba import float64, float64, int32
from pyHype.states.states import ConservativeState
from pyHype.input.input_file_builder import ProblemInput
from pyHype.states.states import primitivestate_type, conservativestate_type, roeprimitivestate_type
from pyHype.input.input_file_builder import propblem_input_type

XDIR_EIGENSYSTEM_VECTORS_SPEC = [('inputs', propblem_input_type),
                                 ('A_d0', float64[:, :]),
                                 ('A_m1', float64[:, :]),
                                 ('A_m2', float64[:, :]),
                                 ('A_m3', float64[:, :]),
                                 ('A_p1', float64[:, :]),
                                 ('A_p2', float64[:, :]),
                                 ('X_d0', float64[:, :]),
                                 ('X_m1', float64[:, :]),
                                 ('X_m2', float64[:, :]),
                                 ('X_m3', float64[:, :]),
                                 ('X_p1', float64[:, :]),
                                 ('X_p2', float64[:, :]),
                                 ('Xi_d0', float64[:, :]),
                                 ('Xi_m1', float64[:, :]),
                                 ('Xi_m2', float64[:, :]),
                                 ('Xi_m3', float64[:, :]),
                                 ('Xi_p1', float64[:, :]),
                                 ('Xi_p2', float64[:, :]),
                                 ('Xi_p3', float64[:, :]),
                                 ('lam', float64[:, :])]

XDIR_EIGENSYSTEM_INDICES_SPEC = [('Ai', int32[:]),
                                 ('Aj', int32[:]),
                                 ('Xi', int32[:]),
                                 ('Xj', int32[:]),
                                 ('Xi_i', int32[:]),
                                 ('Xi_j', int32[:]),
                                 ('Li', int32[:]),
                                 ('Lj', int32[:])]

YDIR_EIGENSYSTEM_VECTORS_SPEC = [('inputs', propblem_input_type),
                                 ('B_d0', float64[:, :]),
                                 ('B_m1', float64[:, :]),
                                 ('B_m2', float64[:, :]),
                                 ('B_m3', float64[:, :]),
                                 ('B_p1', float64[:, :]),
                                 ('B_p2', float64[:, :]),
                                 ('X_d0', float64[:, :]),
                                 ('X_m1', float64[:, :]),
                                 ('X_m2', float64[:, :]),
                                 ('X_m3', float64[:, :]),
                                 ('X_p1', float64[:, :]),
                                 ('X_p2', float64[:, :]),
                                 ('Xi_d0', float64[:, :]),
                                 ('Xi_m1', float64[:, :]),
                                 ('Xi_m2', float64[:, :]),
                                 ('Xi_m3', float64[:, :]),
                                 ('Xi_p1', float64[:, :]),
                                 ('Xi_p2', float64[:, :]),
                                 ('Xi_p3', float64[:, :]),
                                 ('lam', float64[:, :])]

YDIR_EIGENSYSTEM_INDICES_SPEC = [('Bi', int32[:]),
                                 ('Bj', int32[:]),
                                 ('Xi', int32[:]),
                                 ('Xj', int32[:]),
                                 ('Xi_i', int32[:]),
                                 ('Xi_j', int32[:]),
                                 ('Li', int32[:]),
                                 ('Lj', int32[:])]

ROE_FLUX_X_SPEC = [('inputs', propblem_input_type),
                   ('g', float64),
                   ('gh', float64),
                   ('gt', float64),
                   ('gb', float64),
                   ('n', int32),
                   ('nx', int32),
                   ('ny', int32),
                   ('A_d0', float64[:, :]),
                   ('A_m1', float64[:, :]),
                   ('A_m2', float64[:, :]),
                   ('A_m3', float64[:, :]),
                   ('A_p1', float64[:, :]),
                   ('A_p2', float64[:, :]),
                   ('X_d0', float64[:, :]),
                   ('X_m1', float64[:, :]),
                   ('X_m2', float64[:, :]),
                   ('X_m3', float64[:, :]),
                   ('X_p1', float64[:, :]),
                   ('X_p2', float64[:, :]),
                   ('Xi_d0', float64[:, :]),
                   ('Xi_m1', float64[:, :]),
                   ('Xi_m2', float64[:, :]),
                   ('Xi_m3', float64[:, :]),
                   ('Xi_p1', float64[:, :]),
                   ('Xi_p2', float64[:, :]),
                   ('Xi_p3', float64[:, :]),
                   ('lam', float64[:, :]),
                   ('Ai', int32[:]),
                   ('Aj', int32[:]),
                   ('Xi', int32[:]),
                   ('Xj', int32[:]),
                   ('Xi_i', int32[:]),
                   ('Xi_j', int32[:]),
                   ('Li', int32[:]),
                   ('Lj', int32[:])
                   ]

ROE_FLUX_Y_SPEC = [('inputs', propblem_input_type),
                   ('g', float64),
                   ('gh', float64),
                   ('gt', float64),
                   ('gb', float64),
                   ('n', int32),
                   ('nx', int32),
                   ('ny', int32),
                   ('B_d0', float64[:, :]),
                   ('B_m1', float64[:, :]),
                   ('B_m2', float64[:, :]),
                   ('B_m3', float64[:, :]),
                   ('B_p1', float64[:, :]),
                   ('B_p2', float64[:, :]),
                   ('X_d0', float64[:, :]),
                   ('X_m1', float64[:, :]),
                   ('X_m2', float64[:, :]),
                   ('X_m3', float64[:, :]),
                   ('X_p1', float64[:, :]),
                   ('X_p2', float64[:, :]),
                   ('Xi_d0', float64[:, :]),
                   ('Xi_m1', float64[:, :]),
                   ('Xi_m2', float64[:, :]),
                   ('Xi_m3', float64[:, :]),
                   ('Xi_p1', float64[:, :]),
                   ('Xi_p2', float64[:, :]),
                   ('Xi_p3', float64[:, :]),
                   ('lam', float64[:, :]),
                   ('Bi', int32[:]),
                   ('Bj', int32[:]),
                   ('Xi', int32[:]),
                   ('Xj', int32[:]),
                   ('Xi_i', int32[:]),
                   ('Xi_j', int32[:]),
                   ('Li', int32[:]),
                   ('Lj', int32[:])
                   ]
